// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppegyfxaggaorniidyml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwZWd5ZnhhZ2dhb3JuaWlkeW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDc1NjUsImV4cCI6MjA3MjMyMzU2NX0.MVk-VNiLELB-axFFUrUGuwyGwCJ2FlGj_o-uYzBwILc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});